# Generated by Django 3.2.14 on 2022-07-21 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20220721_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='selected_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='selected_time',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='booking',
            name='date_choice',
            field=models.DateField(null=True, verbose_name='Selected Date:'),
        ),
        migrations.AddField(
            model_name='booking',
            name='time_choice',
            field=models.IntegerField(choices=[(0, '9:00'), (1, '10:00'), (2, '11:00')], default=0),
        ),
    ]
