# Generated by Django 3.2.14 on 2022-07-21 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20220721_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='time_choice',
            field=models.CharField(choices=[('9:00', '9:00'), (1, '10:00'), (2, '11:00'), (3, '12:00'), (4, '13:00'), (5, '14:00'), (6, '15:00'), (7, '16:00'), (8, '17:00')], max_length=100),
        ),
    ]
