# Generated by Django 3.2.14 on 2022-07-21 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_auto_20220721_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date_choice',
            field=models.DateField(null=True, verbose_name='Date Choice:'),
        ),
    ]
